import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Precision Architect design system
        'on-tertiary-fixed': '#191e00',
        'outline-variant': '#c5c6ce',
        'inverse-on-surface': '#ecf0ff',
        'secondary-fixed': '#cde5ff',
        'secondary-container': '#a8d3fe',
        'on-primary-fixed-variant': '#3a4664',
        'on-error': '#ffffff',
        'tertiary-container': '#191e00',
        'secondary-fixed-dim': '#a0cbf5',
        'on-error-container': '#93000a',
        'on-surface-variant': '#45464d',
        'tertiary': '#000000',
        'surface-tint': '#525e7d',
        'on-primary': '#ffffff',
        'secondary': '#366287',
        'primary-fixed-dim': '#b9c6e9',
        'primary-container': '#0d1b36',
        'surface-container-low': '#f0f3ff',
        'on-secondary': '#ffffff',
        'surface': '#f9f9ff',
        'surface-dim': '#cedaf6',
        'inverse-primary': '#b9c6e9',
        'on-primary-container': '#7783a4',
        'error': '#ba1a1a',
        'on-tertiary-fixed-variant': '#424b00',
        'background': '#f9f9ff',
        'surface-container-high': '#dfe8ff',
        'tertiary-fixed': '#d9ee59',
        'on-secondary-fixed': '#001d32',
        'primary': '#000000',
        'inverse-surface': '#253146',
        'error-container': '#ffdad6',
        'outline': '#75777e',
        'on-secondary-container': '#2f5b80',
        'surface-container-highest': '#d6e3fe',
        'tertiary-fixed-dim': '#bdd13e',
        'on-background': '#0f1c30',
        'on-primary-fixed': '#0d1b36',
        'surface-variant': '#d6e3fe',
        'surface-bright': '#f9f9ff',
        'on-surface': '#0f1c30',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed-variant': '#1a4a6e',
        'on-tertiary-container': '#7c8c00',
        'primary-fixed': '#d9e2ff',
        'surface-container': '#e8eeff',
        'on-tertiary': '#ffffff',
        'sidebar': '#0A1833',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        handwritten: ['Delicious Handrawn', 'cursive'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      boxShadow: {
        card: '0 8px 24px -4px rgba(15, 28, 48, 0.06)',
        sidebar: '4px 0 24px rgba(10, 24, 51, 0.2)',
      },
    },
  },
  plugins: [],
}

export default config
